name: objectbox_infection_issue
description: Replication for Objectbox infection flagging issue

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  objectbox: ^1.6.2
  objectbox_flutter_libs: ^1.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  objectbox_generator: ^1.6.2

flutter:
  uses-material-design: true
